name: build and push contianer images

on:
  push:
    branches:
    - 'main'
    tags:
    - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push for latest
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/uesyn/dns-resolve-exporter:latest
        if: github.ref_name == 'main'
      - name: Build and push with tag
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/uesyn/dns-resolve-exporter:${{ github.ref_name }}
        if: github.ref_name != 'main'
